services:
  builder:
    image: gbenson/zmachine-builder
    pull_policy: build
    build:
      args:
        BUILDER_IMAGE: ${BUILDER_IMAGE}
        BUILDER_UID: ${BUILDER_UID}
        BUILDER_GID: ${BUILDER_GID}
    hostname: builder
    volumes:
      - go_path:/go
      - go_build_cache:/home/user/.cache/go-build
      - .:/go/src
    working_dir: /go/src

volumes:
  go_path:
  go_build_cache:
  server_data:
