---
- hosts: all

  tasks:
    - name: Unwanted packages are not installed
      ansible.builtin.apt:
        pkg:
          - cloud-init
          - modemmanager
          - rpicam-apps-core
          - rpicam-apps-lite
          - rpi-connect-lite
          - rpi-cloud-init-mods
          - rpi-swap
        state: absent
      become: yes
      tags:
        - packages

    - name: Required packages are installed
      ansible.builtin.apt:
        pkg:
          - git
          - tmux
      become: yes
      tags:
        - packages

    - name: Unwanted systemd units are masked
      ansible.builtin.systemd:
        name: "{{ item }}"
        masked: true
        state: stopped
      loop:
        - swap.target
      become: yes
      tags:
        - services

    - name: Unwanted files don't exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/swap
      become: yes
      tags:
        - filesystem
