---
- hosts: all

  tasks:
    - name: Unwanted packages are not installed
      ansible.builtin.apt:
        pkg:
          - avahi-daemon
          - bluez
          - bluez-firmware
          - cloud-init
          - modemmanager
          - rpicam-apps-core
          - rpicam-apps-lite
          - rpi-connect-lite
          - rpi-cloud-init-mods
          - rpi-swap
        state: absent
      become: yes
      tags:
        - packages

    - name: Required packages are installed
      ansible.builtin.apt:
        pkg:
          - git
          - golang
          - libsdl2-dev
          - tmux
      become: yes
      tags:
        - packages

    - name: Unwanted systemd units are masked
      ansible.builtin.systemd:
        name: "{{ item }}"
        masked: true
        state: stopped
      loop:
        - apt-daily
        - apt-daily.timer
        - apt-daily-upgrade
        - apt-daily-upgrade.timer
        - avahi-daemon
        - avahi-daemon.socket
        - bluetooth
        - man-db.timer
        - swap.target
      become: yes
      tags:
        - services

    - name: Unwanted files don't exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/lib/man-db/auto-update
        - /var/swap
      become: yes
      tags:
        - filesystem

    - name: Bootloader is configured
      ansible.builtin.blockinfile:
        path: /boot/firmware/config.txt
        block: |
          # Disable any boot delay in case zero isn't the default
          boot_delay=0

          # Disable the rainbow splash screen
          disable_splash=1

          # Disable Bluetooth
          dtoverlay=disable-bt

          # Disable composite video output
          enable_tvout=0

          # Enable cut-down firmware. This causes some errors in dmesg
          # (compare `notes/gpu_mem-{16,32}.dmesg`) but saves a chunk
          # of RAM (`free -m` total goes from 416 with default gpu_mem
          # to 464 with `gpu_mem=16`, i.e. the default must be 64 MiB).
          # It also trims about half a second off the boot time.
          gpu_mem=16
      become: yes
      tags:
        - boot

    - name: Bash is configured
      ansible.builtin.copy:
        dest: ~/.bash_aliases
        mode: "0644"
        content: |
          alias ll="ls -l"
          alias rm="rm -i"
          alias cp="cp -i"
          alias mv="mv -i"
      tags:
        - devel

    - name: Git is configured
      ansible.builtin.copy:
        src: ~/.gitconfig
        dest: ~/.gitconfig
        mode: "0644"
      tags:
        - devel
