---
- hosts: all

  tasks:
    - name: Unwanted packages are not installed
      ansible.builtin.apt:
        pkg:
          - avahi-daemon
          - bluez
          - bluez-firmware
          - cloud-init
          - modemmanager
          - rpicam-apps-core
          - rpicam-apps-lite
          - rpi-connect-lite
          - rpi-cloud-init-mods
          - rpi-swap
        state: absent
      become: yes
      tags:
        - packages

    - name: Required packages are installed
      ansible.builtin.apt:
        pkg:
          - git
          - tmux
      become: yes
      tags:
        - packages

    - name: Unwanted systemd units are masked
      ansible.builtin.systemd:
        name: "{{ item }}"
        masked: true
        state: stopped
      loop:
        - avahi-daemon
        - avahi-daemon.socket
        - bluetooth
        - swap.target
      become: yes
      tags:
        - services

    - name: Unwanted files don't exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: absent
      loop:
        - /var/swap
      become: yes
      tags:
        - filesystem

    - name: Bootloader is configured
      ansible.builtin.blockinfile:
        path: /boot/firmware/config.txt
        block: |
          # Disable Bluetooth
          dtoverlay=disable-bt
      become: yes
      tags:
        - boot
